# Generated by Django 3.1.4 on 2021-01-11 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Producerapp', '0001_initial'),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbid',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.producer'),
        ),
        migrations.AddField(
            model_name='productbid',
            name='product_auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producerapp.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.producer'),
        ),
        migrations.AddField(
            model_name='product',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('deleted'), related_name='product_winner', related_query_name='product_winner', to='user_app.consumer'),
        ),
    ]
